window.quizCategories = {
    "Allgemein": [
        { question: "Welches Minievent findet immer im November statt?", answers: ["Tag der Toten","Piratentag","Wanderfest","Ruf des Skarabäus"], correct: "Tag der Toten" },
        { question: "Was bedeutet 'Thrall' wirklich?" , answers: ["Sklave","Erlöser","Bewahrer","Unhold"] , correct: "Sklave" },
        { question: "Wer ist der bekannte Spion der Allianz, der oft verkleidet in Hordenstädten anzutreffen ist?", answers: ["Meister Shaw","Mathias Lehner","Master Mathias","Meister Mathias Shaw"], correct: "Meister Mathias Shaw" },
        { question: "Welche Organisation stellt die Elite-Wachen der Horde in Orgrimmar?", answers: ["Der Zirkel des Blutes","Die Kriegsmeister","Die Kor’kron","Die Donneraxt"], correct: "Die Kor’kron" },
        { question: "Wer war der Anführer der Goblins von Kezan, bevor sie sich der Horde anschlossen?", answers: ["Boss Mida","Gazlowe","Sneed","Handelsprinz Gallywix"], correct: "Handelsprinz Gallywix" },
        { question: "Welche Erweiterung erschien nicht im November?", answers: ["Wrath of the Lich King - 2008","Warlords of Draenor - 2014","Shadowlands - 2020","Burning Crusade - 2007"], correct: "Burning Crusade - 2007" },
        { question: "Welches ist die Heimatwelt der Draenei?", answers: ["Argus", "Outland", "Draenor", "K'aresh"], correct: "Argus" },
        { question: "Was ist der Name des Planeten, auf dem die meiste Handlung von World of Warcraft spielt?", answers: ["Draenor","Argus","Azeroth","K'aresh"], correct: "Azeroth" },
        { question: "Welche Fraktion ist bekannt für ihre lila/goldene Farbgebung und dient oft als neutrale Wächter der Zeit?", answers: ["Der Irdenring","Der Zirkel des Cenarius","Die Kirin Tor","Die Argentum-Dämmerung"], correct: "Die Kirin Tor" },
        { question: "Welcher Drachenschwarm ist für die Bewahrung der Zeitlinie zuständig?", answers: ["Der Rote Drachenschwarm","Der Bronzene Drachenschwarm","Der Grüne Drachenschwarm","Der Blaue Drachenschwarm"], correct: "Der Bronzene Drachenschwarm" },
        { question: "Welcher Begriff beschreibt eine Gruppe von 5 Spielern in einem Dungeon?", answers: ["Schlachtzug","Kommando","Instanzgruppe","Raidgruppe"], correct: "Instanzgruppe" },
        { question: "Was ist der Hauptgrund für den zweiten Krieg zwischen der Horde und der Allianz?", answers: ["Die Öffnung des Dunklen Portals","Der Mord an König Llane","Die Eroberung von Lordaeron","Der Konflikt um Azerit"], correct: "Die Öffnung des Dunklen Portals" },
        { question: "Wer war der Anführer des Bronzebart-Clans der Zwerge vor der Einführung des Rates der Drei Hämmer?", answers: ["König Magni Bronzebart","König Moira Thaurissan","König Falstad Wildhammer","König Varian Wrynn"], correct: "König Magni Bronzebart" },
        { question: "Wer war der erste Kriegshäuptling der Horde?", answers: ["Thrall","Orgrim Schicksalshammer","Blackhand","Uther"], correct: "Blackhand" },
        { question: "Welche Fraktion ist der Hauptfeind in Legion?", answers: ["Die Geißel", "Die Alte Götter", "Die Eiserne Horde", "Die Brennende Legion"], correct: "Die Brennende Legion" },
        { question: "Wie hieß das Turnier, das in Nordend stattfand, um Helden für den Kampf gegen den Lichkönig auszuwählen?", answers: ["Die Kreuzfahrer-Herausforderung","Die Eiskronen-Prüfung","Der Lichkönigs-Gefecht","Argentum-Turnier"], correct: "Argentum-Turnier" },
    ],
    "AddOns": [
        { question: "Wie viele Addons gab es bis 2025?", answers: ["9","10","11","12"], correct: "10" },
        { question: "Wo war Hemet Nesingwary erstmals mit seiner Jagdgesellschaft anzutreffen?", answers: ["Azurblaues Gebirge - Dragonflight","Nagrand - Burning Crusade","Schlingendorntal - Classic","Zuldazar - Battle for Azeroth"], correct: "Schlingendorntal - Classic" },
        { question: "Was war das Levelcap in Classic?", answers: ["50","55","60","70"], correct: "60" },
        { question: "Welche Klasse wurde in The Burning Crusade neu spielbar?", answers: ["Todesritter","Mönch","Dämonenjäger","Keine – nur Rassen"], correct: "Keine – nur Rassen" },
        { question: "Welche Erweiterung brachte den Dungeonfinder ins Spiel?", answers: ["Wrath of the Lich King","Burning Crusade","Cataklysm","Mists of Pandaria"], correct: "Wrath of the Lich King" },
        { question: "Welches AddOn erschien nach Wrath of the Lich King?", answers: ["Warlords of Draenor","Burning Crusade","Mists of Pandaria","Cataclysm"], correct: "Cataclysm" },
        { question: "Wie hieß der Drache aus Cataclysm?", answers: ["Neltharion","Nefarian","Nozdormu","Nathanos"], correct: "Neltharion" },
        { question: "Welche Stadt wurde in Cataclysm zerstört?", answers: ["Darnassus","Theramore","Unterstadt","Gilneas"], correct: "Theramore" },
        { question: "Seit welchem Addon gibt es das Transmog-System?", answers: ["Cataclysm","Mists of Pandaria","Warlords of Draenor","Legion"], correct: "Cataclysm" },
        { question: "Was war das Maximallevel in Mists of Pandaria?", answers: ["85","90","95","100"], correct: "90" },
        { question: "Welches Volk wurde in Warlords of Draenor eingeführt?", answers: ["Vulpera","Orcs","Oger","Kein neues Volk"], correct: "Kein neues Volk" },
        { question: "Welche Erweiterung brachte die Artefaktwaffen?", answers: ["Legion","Warlords of Draenor","Battle for Azeroth","Shadowlands"], correct: "Legion" },
        { question: "Welche Erweiterung brachte die 'Verbündeten Völker'?", answers: ["Warlords of Draenor","Legion","Battle for Azeroth","Shadowlands"], correct: "Battle for Azeroth" },
        { question: "Welches dieser Addons hatte ein Levelcap von 120?", answers: ["Battle for Azeroth","Mists of Pandaria","Warlords of Draenor","Shadowlands"], correct: "Battle for Azeroth" },
        { question: "Wie heißt die Hauptstadt von Dragonflight?", answers: ["Dalaran","Orgrimmar","Dornogal","Valdrakken"], correct: "Valdrakken" },
        { question: "In welchem Add-on wurde das System 'Wissen' für Berufe eingeführt?", answers: ["Shadowlands", "Battle for Azeroth", "Dragonflight", "Legion"], correct: "Dragonflight" },
        { question: "Welche Erweiterung ist die zweite der 'Welten-Seelen-Saga'?", answers: ["The War Within","The Last Titan","Midnight","Dragonflight"], correct: "Midnight" },
        { question: "Welche Klasse konnte man zu Classic nicht spielen?", answers: ["Paladin","Schurke","Mönch","Hexenmeister"], correct: "Mönch" },
        { question: "Was ist das Hauptthema des Addons Shadowlands?", answers: ["Die Invasion der Legion","Der Kampf gegen die Alte Götter","Die Reiche des Todes","Die Dracheninseln"], correct: "Die Reiche des Todes" },
        { question: "Was ist das Hauptthema des Addons Dragonflight?", answers: ["Die Drachenschwärme","Die Eiserne Horde","Die Leere","Die Scherbenwelt"], correct: "Die Drachenschwärme" },
        { question: "Welches Addon führte die Fraktionen 'Aldor' und 'Seher' ein?", answers: ["Wrath of the Lich King","Burning Crusade","Legion","Cataclysm"], correct: "Burning Crusade" },
        { question: "Welches Addon brachte die Zonen Tiefenheim, Uldum und Hyjal?", answers: ["Wrath of the Lich King","Cataclysm","Legion","Shadowlands"], correct: "Cataclysm" },
        { question: "Was war das höchste Levelcap in der Erweiterung *The Burning Crusade*?", answers: ["60","70","80","90"], correct: "70" },
        { question: "In welchem Addon wurde die Archäologie eingeführt?", answers: ["Wrath of the Lich King","Cataclysm","Mists of Pandaria","Warlords of Draenor"], correct: "Cataclysm" },
        { question: "Welches Addon konzentrierte sich auf den Konflikt gegen den Lichkönig Arthas?", answers: ["Cataclysm","Wrath of the Lich King","Burning Crusade","Shadowlands"], correct: "Wrath of the Lich King" },
        { question: "In welchem Addon drehte sich viel um Klassenhallen?", answers: ["Warlords of Draenor","Legion","Battle for Azeroth","Dragonflight"], correct: "Legion" },
        { question: "Was war das Maximallevel in Shadowlands?", answers: ["50","60","70","120"], correct: "60" },
        { question: "Welches Addon führte die Garnison als Spielerbasis ein?", answers: ["Mists of Pandaria","Warlords of Draenor","Battle for Azeroth","Legion"], correct: "Warlords of Draenor" },
        { question: "In welchem Addon bekämpfte man N'Zoth, den Alten Gott?", answers: ["Legion","Battle for Azeroth","Shadowlands","Cataclysm"], correct: "Battle for Azeroth" },
        { question: "Welches Addon brachte die Zonen Hochberg, Val'sharah und Azsuna?", answers: ["Warlords of Draenor","Legion","Battle for Azeroth","Dragonflight"], correct: "Legion" },
        { question: "Was war das ursprüngliche Levelcap in Mists of Pandaria?", answers: ["85","90","100","110"], correct: "90" },
        { question: "Welches Addon erschien vor 'Legion'?", answers: ["Mists of Pandaria","Warlords of Draenor","Cataclysm","Burning Crusade"], correct: "Warlords of Draenor" },
        { question: "Welches Addon führte die Tier-Sets ein?", answers: ["Burning Crusade","Classic","Wrath of the Lich King","Legion"], correct: "Classic" },
        { question: "Welches Addon handelte hauptsächlich von der Eisernen Horde?", answers: ["Burning Crusade","Wrath of the Lich King","Warlords of Draenor","Cataclysm"], correct: "Warlords of Draenor" },
        { question: "Was war das höchste Levelcap in 'Warlords of Draenor'?", answers: ["90","100","110","120"], correct: "100" },
        { question: "Welches Addon führte die Fähigkeit ein, in der alten Welt zu fliegen?", answers: ["Wrath of the Lich King","Cataclysm","Mists of Pandaria","Legion"], correct: "Cataclysm" },
        { question: "Welches Addon brachte die Insel-Expeditionen?", answers: ["Warlords of Draenor","Legion","Battle for Azeroth","Shadowlands"], correct: "Battle for Azeroth" },
        { question: "Welches Addon brachte die Pakte als Feature?", answers: ["Legion","Shadowlands","Dragonflight","Battle for Azeroth"], correct: "Shadowlands" },
        { question: "Welches Addon erschien nach 'Cataclysm'?", answers: ["Burning Crusade","Mists of Pandaria","Warlords of Draenor","Legion"], correct: "Mists of Pandaria" },
        { question: "Was war das höchste Levelcap in 'Legion'?", answers: ["100","110","120","130"], correct: "110" },
        { question: "In welchem Addon wurde die erste große Wiederbelebung der alten Welt-Zonen durchgeführt?", answers: ["Burning Crusade","Wrath of the Lich King","Cataclysm","Mists of Pandaria"], correct: "Cataclysm" },
        { question: "Welches Addon konzentrierte sich auf den Kampf gegen die Brennende Legion?", answers: ["The Burning Crusade","Warlords of Draenor","Legion","Shadowlands"], correct: "Legion" },
        { question: "Welches ist das achte Addon von World of Warcraft?", answers: ["Cataclysm","Mists of Pandaria","Battle for Azeroth","Shadowlands"], correct: "Shadowlands" }
    ],
    "Pets and Mounts": [
        { question: "Wie heißen die Reittiere, die man mit Ruhm bei den Kirin Tor in Wrath of the Lich King freischalten konnte?", answers: ["Phönixe","Greifen","Wasserstoffballons","Arkanwyrmlinge"], correct: "Arkanwyrmlinge" },
        { question: "Welches Mount droppt mit extrem niedriger Chance in Stratholme?", answers: ["Totenschwurs Todesstreitross","Al'ars Asche","Anzu","Unbesiegbar"], correct: "Totenschwurs Todesstreitross" },
        { question: "Welches Haustier bekam man für den 10. Geburtstag von WoW?", answers: ["Klein-Ragnaros","Klein-Illidan","Murloc mit Geburtstagskappe","Geschmolzenes Kernhündchen"], correct: "Geschmolzenes Kernhündchen" },
        { question: "Wie heißt das kleine Mini-Murloc-Maskottchen, das auf vielen BlizzCons verteilt wurde?", answers: ["Murky","Grunty","Murkablo","Mini-Diablo"], correct: "Murky" },
        { question: "Welches Pet bekam man in der Collectors Edition von Burning Crusade?", answers: ["Turtle","Wyrmling","Netherwelpe","Zergling"], correct: "Netherwelpe" },
        { question: "In welchem Gebiet kann man das Mount 'Al'ars Asche' erbeuten?", answers: ["Karazhan", "Festung der Stürme", "Schwarzer Tempel", "Sonnenbrunnenplateau"], correct: "Festung der Stürme" },
        { question: "Welches Haustier bekam man für das Sammeln von 100 Haustieren?", answers: ["Kleiner Blinder","Haustier-Kampfhaustier","Der kleine Sammler","Der kleine Beobachter"], correct: "Der kleine Sammler" },
        { question: "Welches Pet war Teil der Collector's Edition von Wrath of the Lich King?", answers: ["Klein-Arthas","Frostiger Wyrmling","Mini-Lichkönig","Mini-Kel'thuzad"], correct: "Frostiger Wyrmling" },
        { question: "Welches Mount war eine Belohnung für die Teilnahme am Ahn'Qiraj-Öffnungsevent?", answers: ["Der Blaue Qiraji-Resonanzkristall","Der Rote Qiraji-Resonanzkristall","Der Grüne Qiraji-Resonanzkristall","Der Schwarze Qiraji-Resonanzkristall"], correct: "Der Schwarze Qiraji-Resonanzkristall" },
        { question: "Wie nennt man die Reittiere, die man in der Garnison bekommt?", answers: ["Garnisons-Schlachtrösser","Frostwölfe der Garnison","Kriegsbären der Garnison","Eisenhorde-Wölfe"], correct: "Kriegsbären der Garnison" },
        { question: "Welches Reittier droppt mit extrem niedriger Chance in der Eiskronenzitadelle?", answers: ["Totenschwurs Todesstreitross","Al'ars Asche","Anzu","Unbesiegbar"], correct: "Unbesiegbar" },
        { question: "Welches Pet kann man aus dem Geschmolzenen Kern als Drop erhalten?", answers: ["Kernhündchen","Geschmolzenes Kernhündchen","Mini-Ragnaros","Feuerkern"], correct: "Kernhündchen" },
        { question: "Welches Mount droppt mit extrem niedriger Chance in Zul'Gurub?", answers: ["Razzashis Raptoren","Zulianischer Tiger","Schlachtross von Zul'Gurub","Tigersprung"], correct: "Zulianischer Tiger" },
        { question: "Welche Art von Reittieren sind die standardmäßigen Boden-Mounts der Blutelfen?", answers: ["Greifen","Falkenschreiter","Streitrösser","Wölfe"], correct: "Falkenschreiter" },
        { question: "Welche Reittiere sind die standardmäßigen Boden-Mounts der Menschen?", answers: ["Pferde","Greifen","Löwen","Hippogryphen"], correct: "Pferde" },
        { question: "Welches Haustier erhält man durch das Töten von Archimonde im Schwarzen Tempel?", answers: ["Mini-Netherwelpe","Der kleine Netherwelpe","Archimondes Dämonenei","Dämonenwelpe"], correct: "Der kleine Netherwelpe" },
        { question: "Welches Reittier ist der seltene Drop aus der Instanz Sethekk-Hallen?", answers: ["Anzu","Rabenschwinge","Al'ars Asche","Unbesiegbar"], correct: "Anzu" },
    ],
    "Achievements": [
        { question: "Welcher Erfolg schaltet den Titel 'der Verrückte' frei?", answers: ["Der Wahnsinnige","Der Unermüdliche","Der Unerschrockene","Der Verwegene"], correct: "Der Wahnsinnige" },
        { question: "Welchen Titel erhielt man, wenn man alle Ruf-Fraktionen in Classic auf Ehrfürchtig hatte?", answers: ["Der Ehrfürchtige", "Der Wahnsinnige", "Der Diplomat", "Der Makellose"], correct: "Der Diplomat" },
        { question: "Welchen Titel erhielt man für das Töten des Lichkönigs im 25-Spieler-Modus (Heroisch) in der Eiskronenzitadelle?", answers: ["Der Eiskrone-Held","Der Lichtbringer","Der Sturmfresser","Der Königsmörder"], correct: "Der Königsmörder" },
        { question: "Welchen Titel erhielt man für das Erreichen des Höchstrangs im Classic PvP?", answers: ["Feldmarschall/Kriegsfürst","Oberster Krieger/Großmarschall","Der Ehrwürdige","Der Kämpfer"], correct: "Großmarschall" },
        { question: "Welchen Erfolg erhielt man für das Meistern aller primären Berufe (inkl. Angeln und Kochen)?", answers: ["Der Meisterhandwerker","Der Berufstätige","Der Handwerker","Der Alleskönner"], correct: "Der Alleskönner" },
        { question: "Welcher Erfolg wird für das Abschließen aller Dungeons auf dem höchsten Schwierigkeitsgrad in einer Erweiterung vergeben?", answers: ["Ruhm des Helden","Ruhm des Schlachtzugs","Der Dungeon-Meister","Der Unermüdliche"], correct: "Ruhm des Helden" },
        { question: "Wie Viele Haustiere muss man für den Erfolg 'Haustierkämpfer von Azeroth' sammeln?", answers: ["150","200","300","400"], correct: "200" },
        { question: "Welches Reittier erhält man für den Erfolg 'Ruhm des Helden'?", answers: ["Der Violette Protodrache","Der Blutdürstige Reittier","Der Kriegsdrake","Der Eisige Protodrache"], correct: "Der Violette Protodrache" },
        { question: "Wie viele Haustiere muss man für den Erfolg 'Haustierdompteur von Azeroth' sammeln?", answers: ["100","150","200","250"], correct: "150" },
        { question: "Welchen Titel schaltet man durch den Erfolg 'Ehrfürchtig mit 70 Fraktionen' frei?", answers: ["Der Diplomat","Der Erhabene","Der Wahnsinnige","Der Ehrwürdige"], correct: "Der Erhabene" },
        { question: "Welchen Titel erhält man für den Abschluss von 10.000 Quests?", answers: ["Der Entdecker","Der Unermüdliche","Der Questgeber","Der Geschichtenerzähler"], correct: "Der Unermüdliche" },
        { question: "Welcher Erfolg belohnt Spieler mit dem Titel 'der Entdecker'?", answers: ["Erkundet alle Gebiete von Azeroth","Erkundet alle Dungeons","Meistert alle Berufe","Sammelt alle Artefaktwaffen"], correct: "Erkundet alle Gebiete von Azeroth" },
        { question: "Welchen Titel erhielt man für das Töten von Yogg-Saron in Ulduar?", answers: ["Der Unsterbliche","Der Wächter des Geheimnisses","Der Wahnsinnige","Der Lichtbringer"], correct: "Der Wächter des Geheimnisses" },
        { question: "Welchen Titel erhält man für das Erreichen des Höchstrangs im Classic PvP (Allianz)?", answers: ["Feldmarschall","Großmarschall","Kriegsherr","Oberster Krieger"], correct: "Großmarschall" },
        { question: "Welchen Erfolg muss man abschließen, um den Drachen 'Der Violette Protodrache' zu erhalten?", answers: ["Ruhm des Helden","Ruhm des Schlachtzugs","Die Eiskronenzitadelle: Ruhm des Schlachtzüglers","Meistert die Drachenrennen"], correct: "Ruhm des Helden" },
        { question: "Welcher Erfolg ist die Voraussetzung, um den Titel 'der Seemann' freizuschalten?", answers: ["Der Seemann von Kul Tiras","Der Meister der Meere","Der Seemann von Boralus","Der Flottenkommandant"], correct: "Der Seemann von Kul Tiras" },
        { question: "Welchen Titel erhält man für das Töten von Ragnaros in der Feuerlande (Heroisch)?", answers: ["Der Flammenwächter","Der Flammenmeister","Der Feuerlord","Der Glutbringer"], correct: "Der Flammenmeister" },
        { question: "Welchen Erfolg erhält man für das Meistern aller Nebenberufe in Classic?", answers: ["Der Chef","Der Alleskönner","Der Handwerker","Der Abenteurer"], correct: "Der Alleskönner" },
        { question: "Welchen Titel erhielt man für das Erreichen des Höchstrangs im Classic PvP (Horde)?", answers: ["Kriegsfürst","Großkriegsherr","Oberster Krieger","Feldmarschall"], correct: "Großkriegsherr" },
        { question: "Welchen Titel erhielt man für das Töten von Argus dem Zerrütter in Antorus auf dem Mythischen schwierigkeitsgrad?", answers: ["Der Zerrütter der Titanen","Der Titanentöter","Der Seelenernter","Der Erwecker"], correct: "Der Zerrütter der Titanen" },
        { question: "Welchen Titel erhielt man für den Abschluss der Feuerlande Raid-Erfolge?", answers: ["Der Flammenmeister","Der Flammenwächter","Der Feuerlord","Der Glutbringer"], correct: "Der Flammenwächter" },
        { question: "Welchen Titel erhielt man für das Töten von Algalon dem Beobachter in Ulduar?", answers: ["Der Wächter des Geheimnisses","Der Beobachter","Der Titanen-Wächter","Der Unsterbliche"], correct: "Der Beobachter" },
        { question: "Welchen Erfolg erhält man für das Sammeln von 500 Reittieren?", answers: ["Der Stallmeister","Der Große Sammler","Der Reitmeister","Der Reittiersammler"], correct: "Der Stallmeister" },
        { question: "Wie viele Haustiere braucht man für den Erfolg 'Meister-Sammler'?", answers: ["300","500","700","1000"], correct: "700" },
    ],
    "Races and Classes": [
        { question: "Welche Farbe hat der Energiebalken von Wildheitsdruiden?", answers: ["Blau","Gelb","Rot","Grün"], correct: "Gelb" },
        { question: "Welches ist keine Rasse der Horde?", answers: ["Goblin","Gnom","Blutelf","Untote"], correct: "Gnom" },
        { question: "Welche Klasse können 'Kul Tiraner' 2025 nicht werden?", answers: ["Druiden","Schamane","Paladin","Mönch"], correct: "Paladin" },
        { question: "Was war die erste neue spielbare Klasse nach Classic?", answers: ["Dämonenjäger","Todesritter","Mönch","Jäger"], correct: "Todesritter" },
        { question: "Welche Klasse wurde mit Mists of Pandaria neu eingeführt?", answers: ["Mönch","Todesritter","Dämonenjäger","Runenmeister"], correct: "Mönch" },
        { question: "Welche Farbe hat das Mana von Schamanen?", answers: ["Blau","Gelb","Rot","Grün"], correct: "Blau" },
        { question: "Welche spielbare Rasse ist keine Allianz-Rasse?", answers: ["Worgen","Gnome","Blutelfen","Draenei"], correct: "Blutelfen" },
        { question: "Welche Klasse startete zu Classic mit einem Totem-System?", answers: ["Schamane","Druide","Paladin","Priester"], correct: "Schamane" },
        { question: "Welche spielbare Klasse benutzt Runenmacht?", answers: ["Hexenmeister","Todesritter","Dämonenjäger","Mönch"], correct: "Todesritter" },
        { question: "Welche Rasse gilt als Nachfahren der Titanen?", answers: ["Menschen", "Gnome", "Zwerge", "Tauren"], correct: "Zwerge" },
        { question: "Welche Ressource sammelt der Dämonenjäger hauptsächlich im Kampf?", answers: ["Ressentiment", "Wut", "Fokus", "Jähzorn"], correct: "Jähzorn" },
        { question: "Welche Horde-Rasse konnte in Classic kein Jäger werden?", answers: ["Orc", "Tauren", "Troll", "Untoter"], correct: "Untoter" },
        { question: "Welche Horde-Rasse hat traditionell eine hohe Affinität zur Natur und Schamanismus?", answers: ["Orcs", "Goblins", "Tauren", "Blutelfen"], correct: "Tauren" },
        { question: "Welches Volk lebt in Silbermond?", answers: ["Blutelfen","Hochelfen","Nachtelfen","Leerenelfen"], correct: "Blutelfen" },
        { question: "Welche Farbe hatte der Todesritter bei seiner Einführung in Wrath of the Lich King in der Charakterauswahl?", answers: ["Grün", "Rot", "Blau", "Schwarz"], correct: "Rot" },
        { question: "Welche spielbare Rasse wurde in Legion eingeführt?", answers: ["Vulpera","Leerenelfen","Dämonenjäger","Keine Rasse, sondern eine Klasse"], correct: "Keine Rasse, sondern eine Klasse" },
        { question: "Welche Rasse konnte in Classic kein Druide werden?", answers: ["Nachtelfen","Tauren","Trolle","Menschen"], correct: "Menschen" },
        { question: "Welche Volksfertigkeit der Trolle erhöht die Angriffs- und Zaubergeschwindigkeit?", answers: ["Berserker","Regeneration","Wildtiertötung","Tödlichkeit"], correct: "Berserker" },
        { question: "Welche Rasse der Horde dient traditionell als Meisteringenieure und Alchemisten?", answers: ["Goblins","Orcs","Untote","Blutelfen"], correct: "Goblins" },
        { question: "Welche Waffe kann ein Druide nicht anlegen?", answers: ["Stäbe","Dolche","Faustwaffen","Zweihändige Äxte"], correct: "Zweihändige Äxte" },
        { question: "Welches verbündete Volk der Horde sind pfiffige Wüstenbewohner?", answers: ["Mag'har Orcs","Zandalaritrolle","Nachtgeborene","Vulpera"], correct: "Vulpera" },
        { question: "Welche Spezialisierung des Jägers ist hauptsächlich auf den Nahkampf fokussiert?", answers: ["Tierherrschaft","Treffsicherheit","Überleben","Meucheln"], correct: "Überleben" },
        { question: "Welche Rasse hat eine Volksfähigkeit, die einen zweiten Satz von Zauberkräften gewährt?", answers: ["Leerenelfen","Nachtelfen","Draenei","Worgen"], correct: "Nachtelfen" },
        { question: "Welche Ressourcenleiste hat der Krieger primär?", answers: ["Mana","Fokus","Jähzorn","Wut"], correct: "Wut" },
        { question: "Welche spielbare Rasse oder Klasse wurde in Dragonflight eingeführt?", answers: ["Dracthyr","Dämonenjäger","Mönch","Erzmagier"], correct: "Dracthyr" },
        { question: "Welche Farbe hat der Dämonenjäger-Doppelsprung-Effekt?", answers: ["Violett","Grün","Rot","Blau"], correct: "Grün" },
        { question: "Welches der folgenden Schamanen-Totems hatte die Fähigkeit, die kritische Trefferchance zu erhöhen?", answers: ["Totem des Steinhaut","Totem der Erdung","Totem der windzornigen Wut","Totem der Stärke"], correct: "Totem der windzornigen Wut" },
        { question: "Welches Volk der Allianz kam mit der Erweiterung The Burning Crusade ins Spiel?", answers: ["Pandaren","Nachtgeborene","Leerenelfen","Draenei"], correct: "Draenei" },
        { question: "Welches Volk der Horde kam mit der Erweiterung The Burning Crusade ins Spiel?", answers: ["Orcs","Blutelfen","Goblins","Trolle"], correct: "Blutelfen" },
        { question: "Wie nennt man die Wesen, die aus dem ersten Brunnen der Ewigkeit entstanden sind?", answers: ["Hochgeborene","Nachtelfen","Menschen","Zwerge"], correct: "Nachtelfen" },
        { question: "Welches Volk der Allianz ist bekannt für seine Ingenieurskunst?", answers: ["Menschen","Draenei","Gnome","Nachtelfen"], correct: "Gnome" },
        { question: "Welches Volk der Horde ist bekannt für seine Alchemie und Geschäftstüchtigkeit?", answers: ["Trolle","Untote","Orcs","Goblins"], correct: "Goblins" },
        { question: "Welche neue Hauptrasse der Allianz kam in 'Battle for Azeroth' ins Spiel?", answers: ["Leerenelfen","Lichtgeschmiedete Draenei","Kul Tiraner","Dunkleisen-Zwerge"], correct: "Kul Tiraner" },
        { question: "Welche Allianz-Rasse wurde in Legion als Verbündetes Volk hinzugefügt?", answers: ["Nachtgeborene","Mag'har Orcs","Lichtgeschmiedete Draenei","Zandalaritrolle"], correct: "Lichtgeschmiedete Draenei" },
        { question: "Welche Horden-Rasse wurde in Legion als Verbündetes Volk hinzugefügt?", answers: ["Hochbergtauren","Mag'har Orcs","Nachtgeborene","Zandalaritrolle"], correct: "Nachtgeborene" },
        { question: "Welche Farbe hat die magische Energie, die von Dämonen benutzt wird?", answers: ["Arkan-Blau","Schatten-Violett","Fel-Grün","Licht-Gelb"], correct: "Fel-Grün" },
        { question: "Welche Allianz-Rasse hat die Volksfähigkeit 'Steingestalt'?", answers: ["Menschen","Zwerge","Gnome","Draenei"], correct: "Zwerge" },
        { question: "Welche Klasse ist bekannt für die Ressource Seelensplitter?", answers: ["Magier","Priester","Hexenmeister","Schurke"], correct: "Hexenmeister" },
        { question: "Welche Klasse verwendet die Ressource Heilige Kraft?", answers: ["Priester","Paladin","Mönch","Druide"], correct: "Paladin" },
        { question: "Welche Horde-Rasse ist bekannt für ihre Regeneration-Fähigkeit?", answers: ["Trolle","Orcs","Untote","Goblins"], correct: "Trolle" },
        { question: "Welche Klasse wurde mit der Erweiterung Legion neu spielbar?", answers: ["Mönch","Todesritter","Dämonenjäger","Rufer der Dracthyr"], correct: "Dämonenjäger" },
        { question: "Welche Ressource sammelt der Schurke primär im Kampf?", answers: ["Wut","Fokus","Energie","Chi"], correct: "Energie" },
        { question: "Welche Klasse konnte in Classic nur von Allianz-Völkern gespielt werden?", answers: ["Schamane","Druide","Paladin","Jäger"], correct: "Paladin" },
        { question: "Welche Klasse konnte in Classic nur von Horde-Völkern gespielt werden?", answers: ["Paladin","Priester","Schamane","Krieger"], correct: "Schamane" },
        { question: "Welche Klasse nutzt das Tierbegleiter-System als zentrale Mechanik?", answers: ["Druide","Hexenmeister","Jäger","Schamane"], correct: "Jäger" },
        { question: "Welche Klasse wurde mit der Erweiterung Dragonflight eingeführt?", answers: ["Mönch","Dämonenjäger","Rufer","Todesritter"], correct: "Rufer der Dracthyr" },
        { question: "Welche Ressource nutzt der Mönch neben Energie?", answers: ["Wut","Jähzorn","Chi","Seelensplitter"], correct: "Chi" },
        { question: "Welche Rasse der Horde ist bekannt für ihre Fähigkeit, Voodoo und Loa zu verehren?", answers: ["Orcs","Untote","Tauren","Trolle"], correct: "Trolle" },
        { question: "Welche Klasse ist bekannt für die Fähigkeit 'Aura des Kreuzfahrers'?", answers: ["Krieger","Paladin","Todesritter","Priester"], correct: "Paladin" }
    ],
    "Dungeons and Raids": [
        { question: "Wer ist der Endboss in der 'Thron des Donners'-Instanz?", answers: ["Lei Shen","Garrosh Höllschrei","Ragnaros","Zul'jin"], correct: "Lei Shen" },
        { question: "Wann ging es zurück nach Karazhan?", answers: ["Battle for Azeroth","Warlords of Draenor","Legion","Cataclysm"], correct: "Legion" },
        { question: "Wie viele Spieler waren für Raids in Classic vorgesehen?", answers: ["10","20","25","40"], correct: "40" },
        { question: "Welche Instanz in Classic war die erste mit 20 Spielern?", answers: ["Onyxias Hort","Zul'Gurub","Geschmolzener Kern","Pechschwingenhort"], correct: "Zul'Gurub" },
        { question: "Welche alte Gottheit lag unter dem Tempel von Ahn’Qiraj?", answers: ["C’Thun","Yogg-Saron","N’Zoth","Y’Shaarj"], correct: "C’Thun" },
        { question: "Wie heißt der erste Raid in Classic WoW?", answers: ["Geschmolzener Kern","Zul'Gurub","Pechschwingenhort","Onyxias Hort"], correct: "Geschmolzener Kern" },
        { question: "Wie viele Spieler waren ursprünglich für Onyxias Hort vorgesehen?", answers: ["10","20","25","40"], correct: "40" },
        { question: "Wie viele Flügel hat Naxxramas?", answers: ["3","4","5","6"], correct: "4" },
        { question: "Welcher Boss war Endgegner in 'Der Pechschwingenhort'?", answers: ["Ragnaros","Nefarian","Onyxia","Chromaggus"], correct: "Nefarian" },
        { question: "Welcher Raidboss war Endgegner in 'Der Geschmolzene Kern'?", answers: ["Onyxia","Ragnaros","Majordomus Exekutus","Geddon"], correct: "Ragnaros" },
        { question: "Wie viele Bosse befinden sich in der klassischen Instanz 'Die Todesminen', ohne den Endboss?", answers: ["3", "4", "5", "6"], correct: "5" },
        { question: "Wer war der letzte Boss in Karazhan?", answers: ["Prinz Malchezaar","Moroes","Kurator","Medivh"], correct: "Prinz Malchezaar" },
        { question: "Wie heißt der erster Raid in Burning Crusade?", answers: ["Gruuls Unterschlupf","Karazhan","Magtheridons Kammer","Hyjalgipfel"], correct: "Karazhan" },
        { question: "Welcher Dungeon ist bekannt für den Boss 'Anzu' und das dazugehörige Mount?", answers: ["Sethekk-Hallen", "Schattenlabyrinth", "Auchenai-Krypta", "Die Mechanar"], correct: "Sethekk-Hallen" },
        { question: "Wie heißt der Endboss von Wrath of the Lich King?", answers: ["Arthas Menethil","Kel'Thuzad","Illidan Sturmgrimm","Deathwing"], correct: "Arthas Menethil" },
        { question: "Welcher Boss in Ulduar war optional und besonders schwer?", answers: ["Algalon der Beobachter","Yogg-Saron","Mimiron","Thorim"], correct: "Algalon der Beobachter" },
        { question: "Wer war der erste Boss in der Eiskronenzitadelle?", answers: ["Lord Mark’gar","Lady Todeswisper","Professor Seuchenmord","Sindragosa"], correct: "Lord Mark’gar" },
        { question: "Welches große Schiff war das Flaggschiff der Allianz in der Eiskronenzitadelle?", answers: ["Die Himmelsschrecken", "Die Donnerzorn", "Die Geißelbringer", "Die Sturmwinde"], correct: "Die Himmelsschrecken" },
        { question: "Welcher Boss in der Eiskronenzitadelle hat die berüchtigte 'Verschlingende Plage' Fähigkeit?", answers: ["Professor Seuchenmord", "Sindragosa", "Könige im gefallenen Reich", "Fauldarm"], correct: "Fauldarm" },
        { question: "Wer war der letzte Boss in 'Drachenseele'?", answers: ["Malygos","Todesschwinge","Neltharion","Sinestra"], correct: "Todesschwinge" },
        { question: "Mit welchem Raid wurde der mythische Raidmodus eingeführt?", answers: ["Terrasse des Endlosen Frühlings","Thron des Donners","Schlacht um Orgrimmar","Das Herz der Angst"], correct: "Schlacht um Orgrimmar" },
        { question: "In welche Instanz ging es erneut in Mists of Pandaria?", answers: ["Das Scharlachrote Kloster","Metbrauerei Glutbräu","Auchindoun","Todesminen"], correct: "Das Scharlachrote Kloster" },
        { question: "Wer war der letzte Boss in der Schlacht um Orgrimmar?", answers: ["Garrosh Höllschrei","Varok Saurfang","Thrall","Anduin Wrynn"], correct: "Garrosh Höllschrei" },
        { question: "Wie hieß die letzte Instanz in Warlords of Draenor?", answers: ["Schwarzfelsgießerei","Hochfels","Höllenfeuerzitadelle","Obere Schwarzfelsspitze"], correct: "Höllenfeuerzitadelle" },
        { question: "Wer war der Endboss von Legion?", answers: ["Kil’jaeden","Sargeras","Argus der Zerrütter","Illidan"], correct: "Argus der Zerrütter" },
        { question: "Welcher Raid endete mit dem Kampf gegen Gul’dan?", answers: ["Die Nachtfestung","Höllenfeuerzitadelle","Grabmal des Sargeras","Schwarzfelsgießerei"], correct: "Grabmal des Sargeras" },
        { question: "Welches ist kein Raid aus Battle for Azeroth?", answers: ["Schlacht von Dazar'alor","Tiegel der Stürme","Der Ewige Palast","Der Schrein des Sturms"], correct: "Der Schrein des Sturms" },
        { question: "Welcher Raid war Teil von Battle for Azeroth?", answers: ["Schlacht von Dazar’alor","Tempel von Ahn’Qiraj","Onyxias Hort","Sanktum der Herrschaft"], correct: "Schlacht von Dazar’alor" },
        { question: "Wie heißt der erste Raid in Shadowlands?", answers: ["Sanktum der Herrschaft","Schloss Nathria","Mausoleum der Ersten","Tiegel der Stürme"], correct: "Schloss Nathria" },
        { question: "In welcher Instanz bekämpfte man den verrückten König Ymiron?", answers: ["Uldaman","Schwarzfelstiefen","Burg Utgarde","Gundrak"], correct: "Burg Utgarde" },
        { question: "Welcher Dungeon ist bekannt für Lady Vashj?", answers: ["Schlangenschrein","Höhlen des Wehklagens","Pechschwingenhort","Der Ewige Palast"], correct: "Der Ewige Palast" },
        { question: "Welcher Raid endete mit einem Kampf gegen den Alten Gott C’Thun?", answers: ["Ulduar","Der Geschmolzene Kern","Der Schwarze Tempel","Tempel von Ahn'Qiraj"], correct: "Tempel von Ahn'Qiraj" },
        { question: "In welchem Dungeon bekämpfte man Baron Ashbury?", answers: ["Schattenhochland","Burg Schattenfang","Scharlachrotes Kloster","Der Versunkene Tempel"], correct: "Burg Schattenfang" },
        { question: "Wie heißt die schwebende Zitadelle, die Naxxramas im Himmel trägt?", answers: ["Acherus","Kel'Thuzads Festung","Die Nekropole","Das Auge"], correct: "Die Nekropole" },
        { question: "In welcher Instanz traf man den Boss 'Der Kurator'?", answers: ["Schloss Nathria","Karazhan","Der Tempel von Ahn'Qiraj","Ulduar"], correct: "Karazhan" },
        { question: "Welcher Boss im Geschmolzenen Kern musste zuerst besiegt werden, bevor man Ragnaros herausfordern konnte?", answers: ["Baron Geddon","Garr","Majordomus Exekutus","Sulfuronherold"], correct: "Majordomus Exekutus" },
        { question: "Welcher Raidboss im Pechschwingenhort war bekannt dafür, die Gedanken der Spieler zu übernehmen?", answers: ["Nefarian","Vaelastrasz der Gebundene","Chromaggus","Feuerkralle der Ungezähmte"], correct: "Vaelastrasz der Gebundene" },
        { question: "Wie hieß der Boss im Thron der Vier Winde, der aus drei Bossen bestand?", answers: ["Al'Akir","Die Konklave des Windes","Halion","Nefarian"], correct: "Die Konklave des Windes" },
        { question: "Wie heißt die Stadt, die durch die Zeit verschoben wurde und als Dungeon diente?", answers: ["Nachtfestung","Karazhan","Schwarzer Tempel","Das Verlies"], correct: "Karazhan" },
        { question: "Wer ist der letzte Boss in 'Sanktum der Herrschaft'?", answers: ["Der Kerkermeister","Sylvanas Windläufer","Kel'Thuzad","Tarragrue"], correct: "Sylvanas Windläufer" },
        { question: "In welcher Zone befindet sich die Burg Nathria?", answers: ["Maldraxxus","Revendreth","Ardenwald","Oribos"], correct: "Revendreth" },
        { question: "Welcher Raid endete mit dem Kampf gegen Raszageth die Sturmfresserin?", answers: ["Gewölbe der Inkarnationen","Aberrus","Amirdrassil","Der Smaragdgrüne Traum"], correct: "Gewölbe der Inkarnationen" },
        { question: "Wie hieß der finale Boss von Maraudon?", answers: ["Lord Celestron","Zauberin Seli'na","Fürst Vilefang","Prinzessin Theradras"], correct: "Prinzessin Theradras" },
        { question: "Welcher der folgenden Bosse war kein Endboss der 'Festung der Stürme'-Instanzen?", answers: ["Kael'thas Sonnenwanderer","Warpmeister Spitzzahn","Hochbotaniker Freya","Leerrufer Yal'Jat"], correct: "Hochbotaniker Freya" },
        { question: "Welche Schlacht endete mit dem Fall von Garrosh Höllschrei als Kriegshäuptling?", answers: ["Schlacht um Dazar'alor","Schlacht am Hyjal","Schlacht um Orgrimmar","Schlacht um die Eiskronenzitadelle"], correct: "Schlacht um Orgrimmar" },
        { question: "Was ist der Name der größten militärischen Festung der Geißel in Nordend?", answers: ["Naxxramas","Ulduar","Die Eiskronenzitadelle","Burg Utgarde"], correct: "Die Eiskronenzitadelle" },
        { question: "Wer war der Endboss im Raid Der Schwarze Tempel?", answers: ["Kael'thas Sonnenwanderer","Lady Vashj","Illidan Sturmgrimm","Archimonde"], correct: "Illidan Sturmgrimm" },
        { question: "Welcher Raid in Mists of Pandaria spielte in der Nähe der Jadewald-Zone?", answers: ["Thron des Donners","Mogu'shan-Gewölbe","Schlacht um Orgrimmar","Das Herz der Angst"], correct: "Mogu'shan-Gewölbe" }
    ],
    "Quests and Regions": [
        { question: "Welche Waffe war der Pre-Quest-Loot von Ragnaros in Geschmolzener Kern?", answers: ["Donnerzorn","Aschenbringer","Atiesh","Sulfuronhammer"], correct: "Sulfuronhammer" },
        { question: "Welche Fraktion half der Horde, die Stadt Shattrath zu erreichen?", answers: ["Die Aldor","Die Seher","Die Shat'ar","Die Expedition der Horde"], correct: "Die Seher" },
        { question: "Welche Fraktion lieferte die Quest für das T0.5 Dungeon-Set in Classic?", answers: ["Argentum-Dämmerung","Der Zirkel des Blutes","Die Aldor","Die Cenarische Expedition"], correct: "Argentum-Dämmerung" },
        { question: "Welches legendäre Item bekam man in Classic durch eine Quest in Geschmolzener Kern?", answers: ["Sulfuras, Hand von Ragnaros","Schattenmourne","Donnerzorn, Gesegnete Klinge des Windsuchers","Aschenbringer"], correct: "Sulfuras, Hand von Ragnaros" },
        { question: "Wie heißt der Kontinent, der in der Erweiterung Cataclysm eingeführt wurde?", answers: ["Nordend","Pandaria","Östliches Königreich","Es wurde kein neuer Kontinent eingeführt"], correct: "Es wurde kein neuer Kontinent eingeführt" },
        { question: "Welche Zone wurde mit Cataclysm in zwei Level-Bereiche geteilt?", answers: ["Schlingendorntal","Das Brachland","Schattenhochland","Arathihochland"], correct: "Das Brachland" },
        { question: "Welche Region war in Cataclysm neu?", answers: ["Uldum","Nordend","Schlingendorntal","Das Brachland"], correct: "Uldum" },
        { question: "Welches Gebiet sieht wie das Hordelogo aus?", answers: ["Tanaris","Azshara","Schattenhochland","Sümpfe des Elends"], correct: "Azshara" },
        { question: "Welche Zone war das Startgebiet der Todesritter?", answers: ["Geisterlande","Tirisfal","Östliche Pestländer","Westliche Pestländer"], correct: "Östliche Pestländer" },
        { question: "Wie heißt der Kontinent, auf dem Sturmwind ist?", answers: ["Kalimdor","Östliche Pestländer","Östliches Königreich","Azeroth"], correct: "Östliches Königreich" },
        { question: "Welche Zone liegt nicht in Nordend?", answers: ["Boreanische Tundra","Grizzlyhügel","Eiskrone","Schattenmondtal"], correct: "Schattenmondtal" },
        { question: "Wie heißt die Hauptstadt der Untoten?", answers: ["Unterstadt","Silbermond","Tirisfal","Lordaeron"], correct: "Unterstadt" },
        { question: "Wie hieß die ursprüngliche Hauptstadt der Nachtelfen?", answers: ["Suramar","Darnassus","Zin-Azshari","Ashenvale"], correct: "Zin-Azshari" },
        { question: "Welche Hauptstadt der Horde liegt in Kalimdor?", answers: ["Unterstadt","Orgrimmar","Silbermond","Shattrath"], correct: "Orgrimmar" },
        { question: "Welche Zone ist kein Startgebiet?", answers: ["Dun Morogh","Mulgore","Dämmerwald","Teldrassil"], correct: "Dämmerwald" },
        { question: "Welche Zone ist Heimat der Tauren?", answers: ["Durotar","Mulgore","Brachland","Feralas"], correct: "Mulgore" },
        { question: "Wie heißt die schwebende Stadt der Kirin Tor?", answers: ["Shattrath", "Boralus", "Dalaran", "Oribos"], correct: "Dalaran" },
        { question: "Wie heißt der große Baum, den die Nachtelfen nach der Zerstörung des ersten Brunnen der Ewigkeit pflanzten?", answers: ["Nordrassil", "Teldrassil", "Vordrassil", "Andrassil"], correct: "Nordrassil" },
        { question: "In welchem Gebiet befindet sich der 'Tempel der Erde'?", answers: ["Tiefenheim","Kun-Lai-Gipfel","Thaldraszus","Drachenöde"], correct: "Tiefenheim" },
        { question: "Wo befindet sich die 'Zeitlose Insel'?", answers: ["Östlich in Pandaria","Nördlich auf den Dracheninseln","Westlich im Mahlstrom","Südlich in Zandalar"], correct: "Östlich in Pandaria" },
        { question: "Wie heißt die Hauptstadt der Nachtgeborenen?", answers: ["Shattrath","Suramar","Silbermond","Telogrus"], correct: "Suramar" },
        { question: "Wie viele Inseln bilden die 'Verheerten Inseln'?", answers: ["3","4","5","6"], correct: "5" },
        { question: "In welcher Zone befindet sich die Stadt Gadgetzan?", answers: ["Tanaris","Brachland","Thousand Needles","Silitus"], correct: "Tanaris" },
        { question: "In welchem Gebiet beginnt die Allianz-Questreihe für Gnom- und Zwergen-Charaktere?", answers: ["Ewige Warte","Dun Morogh","Teldrassil","Wald von Elwynn"], correct: "Dun Morogh" },
        { question: "Welche Zone in Kalimdor ist bekannt für die 'Teufelssaurier'?", answers: ["Feralas","Krater von Un'Goro","Brachland","Durotar"], correct: "Krater von Un'Goro" },
        { question: "Wie heißt der Gasthof in Goldhain?", answers: ["Zum Wilden Eber","Zum Trunkenen Drachen","Zum Roten Schwert","Zum Pfeifenden Schwein"], correct: "Zum Pfeifenden Schwein" },
        { question: "Welcher Kontinent wurde in der vierten Erweiterung primär erkundet?", answers: ["Nordend","Die Verheerten Inseln","Pandaria","Kul Tiras"], correct: "Pandaria" },
        { question: "Welche Zone wurde in 'Cataclysm' unter Wasser gesetzt?", answers: ["Desolace","Brachland","Tausend Nadeln","Die Sümpfe des Elends"], correct: "Tausend Nadeln" },
        { question: "Wo befindet sich die Halle des Lichts, die Klassenhalle der Paladine in Legion?", answers: ["Sturmheim","Der Immersangwald","Die Vergessene Küste","Die Kapelle des Hoffnungsvollen Lichts"], correct: "Die Kapelle des Hoffnungsvollen Lichts" },
        { question: "Welche Zone war die erste, die man in Nordend betrat, wenn man mit dem Schiff anreiste?", answers: ["Drachenöde","Eiskrone","Boreanische Tundra","Grizzlyhügel"], correct: "Boreanische Tundra" },
        { question: "Welche Stadt ist das Zentrum des Handelns in Boralus?", answers: ["Der Hafen","Die Handelskammer","Der Freudenmarkt","Der Markt des Meeres"], correct: "Der Markt des Meeres" },
        { question: "Welche Region wurde die Startzone der Worgen?", answers: ["Gilneas","Dämmerwald","Tol Barad","Argentumwald"], correct: "Gilneas" },
        { question: "Wie heißt die Hauptbasis der Allianz in Draenor?", answers: ["Sturmschild","Die Zuflucht des Archons","Sturmwind-Bolzen","Ashran"], correct: "Sturmschild" },
        { question: "Wie heißt das Gebiet, dass die Hauptstadt der Allianz, Valgarde, enthält?", answers: ["Sturmwind","Drachenöde","Eiskrone","Heulender Fjord"], correct: "Heulender Fjord" },
        { question: "In welcher Zone bekämpfte man Helya, die Anführerin der Val'kyr?", answers: ["Sturmheim","Val'sharah","Hochberg","Azsuna"], correct: "Sturmheim" },
        { question: "Welche Hauptstadt der Horde in Battle for Azeroth ist ein riesiges goldenes Pyramiden-Gebäude?", answers: ["Zuldazar","Nazjatar","Dazar'alor","Boralus"], correct: "Dazar'alor" },
        { question: "Wo befand sich die Klassenhalle des Hexenmeisters?", answers: ["Das Verlies von Karazhan","Der Smaragdgrüne Traum","Die Zwielichtzone","Die Schreckensnarbe"], correct: "Die Schreckensnarbe" },
        { question: "Was ist der Name des großen Kontinents im Osten von Azeroth?", answers: ["Kalimdor","Nordend","Östliches Königreich","Pandaria"], correct: "Östliches Königreich" },
        { question: "Was ist der Name des großen Kontinents im Westen von Azeroth?", answers: ["Östliches Königreich","Kalimdor","Scherbenwelt","Dracheninseln"], correct: "Kalimdor" },
        { question: "Welche Stadt dient als neutrale Hauptstadt im Scherbenwelt-Addon?", answers: ["Dalaran","Boralus","Shattrath","Silbermond"], correct: "Shattrath" },
        { question: "Welche Hauptstadt wurde zu Beginn von Battle for Azeroth zerstört?", answers: ["Unterstadt","Silbermond","Darnassus","Gnomeregan"], correct: "Darnassus" },
        { question: "Wie heißt der Ort, an dem das 'Dunkle Portal' liegt?", answers: ["Der Schwarze Sumpf","Die Verwüsteten Lande","Die Brennende Steppe","Die Östlichen Pestländer"], correct: "Die Verwüsteten Lande" },
        { question: "Wie heißt die Insel, auf der die Allianz-Hauptstadt Exodar abgestürzt ist?", answers: ["Die Blutmythos-Insel","Die Azuremyst-Insel","Kezan","Teldrassil"], correct: "Die Azuremyst-Insel" },
        { question: "In welchem Addon wurde das Tal der Ewigen Blüten in Pandaria angegriffen und verändert?", answers: ["Warlords of Draenor","Mists of Pandaria","Cataclysm","Legion"], correct: "Mists of Pandaria" },
        { question: "Welche Einheit des Spiels dient als Hauptquartier für die Todesritter?", answers: ["Eiskronenzitadelle","Acherus","Schwarze Festung","Schattenschmiede"], correct: "Acherus" },
        { question: "Wie hieß der Kontinent, der in 'Mists of Pandaria' eingeführt wurde?", answers: ["Nordend","Scherbenwelt","Pandaria","Dracheninseln"], correct: "Pandaria" },
        { question: "Wie hieß die Haupt-Zone, die in 'The Burning Crusade' erkundet wurde?", answers: ["Nordend","Pandaria","Scherbenwelt","Azeroth"], correct: "Scherbenwelt" },
        { question: "Welche Zone in Nordend ist bekannt für die riesigen Mammuts und Grizzlys?", answers: ["Drachenöde","Eiskrone","Boreanische Tundra","Grizzlyhügel"], correct: "Grizzlyhügel" },
        { question: "Welcher Kontinent wurde in der Erweiterung Wrath of the Lich King primär erkundet?", answers: ["Kalimdor","Nordend","Östliches Königreich","Pandaria"], correct: "Nordend" },
        { question: "Welche Zone in den Östlichen Königreichen ist bekannt für die Scharlachrote Enklave?", answers: ["Östliche Pestländer","Westliche Pestländer","Tirisfal","Silberwald"], correct: "Tirisfal" },
        { question: "Wie wird die Kraftquelle genannt, die einst in Quel'Thalas zerstört wurde?", answers: ["Sonnenbrunnen","Brunnen der Ewigkeit","Mondbrunnen","Quel’Danas"], correct: "Sonnenbrunnen" },
    ],
    "NPCs": [
        { question: "Welcher Gegner in Uldaman spielt auf den Film 'Indiana Jones' an?", answers: ["Arkanist Janna","Der Kurator","Reaver-Droid","Archäologe Korthos"], correct: "Archäologe Korthos" },
        { question: "Welcher Boss im Grabmal des Sargeras war ein Dämonenlord, der die Brennende Legion anführte?", answers: ["Kil'jaeden","Archimonde","Gul'dan","Sargeras"], correct: "Kil'jaeden" },
        { question: "Welcher alte Gott lag unter Ulduar?", answers: ["C’Thun","N’Zoth","Yogg-Saron","Y’Shaarj"], correct: "Yogg-Saron" },
        { question: "Welcher Pakt in Shadowlands hat sich der Wiedergeburt der Natur verschrieben?", answers: ["Venthyr", "Kyrianer", "Nachtfae", "Nekrolords"], correct: "Nachtfae" },
        { question: "Welcher Pakt hat seine Basis in der Zone Maldraxxus?", answers: ["Kyrianer", "Nekrolords", "Nachtfae", "Venthyr"], correct: "Nekrolords" },
        { question: "Wer war kein Anführer der Horde?", answers: ["Arthas","Vol'jin","Thrall","Garrosh"], correct: "Arthas" },
        { question: "Wer oder was ist 'Michael 'Schmutz' Fink'?", answers: ["Angellehrer in Theramore","Kochlehrer in Sturmwind","Flugmeister in Gilneas","Gastwirt in Boralus"], correct:"Angellehrer in Theramore" },
        { question: "Welcher bekannte Charakter ist nicht Teil der Windläufer-Familie?", answers: ["Alleria","Sylvanas","Vereesa","Tyrande"], correct: "Tyrande" },
        { question: "Wie hieß die Orc-Frau, die Thrall in Durnholde erzogen hat?", answers: ["Draka","Aggra","Taretha","Geyah"], correct: "Taretha" },
        { question: "Welcher Drache half bei der Erschaffung der Dämonenseele?", answers: ["Malygos","Neltharion","Nozdormu","Alexstrasza"], correct: "Neltharion" },
        { question: "Wofür sind Murlocs berühmt?", answers: ["Ihre Kampfkraft","Ihre epischen Quests","Ihre Sprache","Ihr Gurgl-Geräusch"], correct: "Ihr Gurgl-Geräusch" },
        { question: "Welche Klasse war Arthas Menethil vor seiner Verwandlung?", answers: ["Paladin","Priester","Krieger","Todesritter"], correct: "Paladin" },
        { question: "Wer war der erste Anführer der Verlassenen?", answers: ["Sylvanas","Varimathras","Kel'Thuzad","Putress"], correct: "Sylvanas" },
        { question: "Wer schmiedete die ursprüngliche Frostgram?", answers: ["Der Lichkönig","Kil’jaeden","Ner’zhul","Die Nathrezim"], correct: "Die Nathrezim" },
        { question: "Welcher Drache wurde zum Aspekt der Zeit?", answers: ["Nozdormu","Malygos","Ysera","Kalecgos"], correct: "Nozdormu" },
        { question: "Wie heißt der Begleiter von Thrall?", answers: ["Schneesang","Schneewehe","Schneegipfel","Schneesturm"], correct: "Schneesang" },
        { question: "Wie lautet Thralls richtiger Name?" , answers: ["Thrall","Go'el","Helot","Thralldom"], correct: "Go'el" },
        { question: "Wer ist der Gründer der Argentum-Dämmerung?", answers: ["Tirion Fordring", "Darion Mograine", "Lord Maxwell Tyrosus", "Uther Lichtbringer"], correct: "Lord Maxwell Tyrosus" },
        { question: "Wer ist der Vater von Thrall?", answers: ["Orgrim Schicksalshammer","Durotan","Garrosh Höllschrei","Grom Höllschrei"], correct: "Durotan" },
        { question: "Wer ist die Mutter von Thrall?", answers: ["Aggra", "Draka", "Taretha", "Geya'rah"], correct: "Draka" },
        { question: "Wie heißt der Vater von König Varian Wrynn?", answers: ["Anduin Wrynn", "Llane Wrynn", "Turalyon Wrynn", "Terenas Menethil"], correct: "Llane Wrynn" },
        { question: "Welche Rolle übernimmt Anduin Wrynn hauptsächlich im Spiel?", answers: ["Tank","Heiler","DPS","Er ist kein Kämpfer"], correct: "Heiler" },
        { question: "Welcher Charakter war nicht Mitglied der 'Scharlachroten Flamme'?", answers: ["Sally Weißsträhne","Renault Mograine","Whitemane","Uther"], correct: "Uther" },
        { question: "Wie heißt der grüne Netherdrache im Unteren Viertel?", answers: ["Barthamus","Malfas","Jorus","Zoya"], correct: "Zoya" },
        { question: "Wie heißt der Allianzanführer aus 'Die Exodar'?", answers: ["Prophet Velen","Hochexarch Turalyon","Valeera Sanguinar","Vereesa Windläufer"], correct: "Prophet Velen" },
        { question: "Welcher Charakter sagt 'Ihr seid noch nicht vorbereitet!'?", answers: ["Illidan","Arthas","Thrall","Sylvanas"], correct: "Illidan" },
        { question: "Welcher Ruffraktion gehört 'König Yokkum' an?", answers: ["Die Söhne Hodirs","Die Kalu'ak","Die Taunka","Der Wyrmruhpakt"], correct: "Die Söhne Hodirs" },
        { question: "Welches Volk lebt in Eiskrone im Gebiet der Kalu’ak?", answers: ["Trolle","Taunka","Murlocs","Goblins"], correct: "Taunka" },
        { question: "Wer tötete König Varian Wrynn?", answers: ["Sargeras","Gul’dan","Orcische Höllenschmiede","Gul’dan & die Legion"], correct: "Gul’dan & die Legion" },
        { question: "Wer wurde nach Vol’jins Tod Kriegshäuptling der Horde?", answers: ["Sylvanas Windläufer","Thrall","Garrosh Höllschrei","Cairne Bluthuf"], correct: "Sylvanas Windläufer" },
        { question: "Wer oder was ist 'Antros'?", answers: ["Gastwirt in Oribos","Questmob in Maldraxxus","Weltboss in Zereth Mortis","Händler im Schlund"], correct: "Weltboss in Zereth Mortis" },
        { question: "Wer führte die Allianz in der Schlacht um Lordaeron an?", answers: ["König Varian Wrynn","Prophet Velen","Genn Graumähne","Anduin Wrynn"], correct: "Anduin Wrynn" },
        { question: "Welcher Charakter sagte: 'Ich diene... dem wahren Kriegshäuptling'?", answers: ["Sylvanas Windläufer","Garrosh Höllschrei","Varok Saurfang","Thrall"], correct: "Varok Saurfang" },
        { question: "Welches ist kein Mitglied des Schwarzen Drachenschwarms?", answers: ["Nefarian","Onyxia","Sabellian","Malygos"], correct: "Malygos" },
        { question: "Wer schuf die Geißel?", answers: ["Kil'jaeden","Sargeras","Ner'zhul","Der Lichkönig"], correct: "Ner'zhul" },
        { question: "Welche Fraktion ist der Hauptgegner in der ursprünglichen Warcraft-Saga?", answers: ["Die Geißel","Die Alten Götter","Die Eiserne Horde","Die Brennende Legion"], correct: "Die Brennende Legion" },
        { question: "Wie lautet der Name des ersten Lichkönigs?", answers: ["Arthas Menethil","Bolvar Fordragon","Kel'Thuzad","Ner'zhul"], correct: "Ner'zhul" },
        { question: "Wer ist der Anführer der Blutelfen?", answers: ["Lor'themar Theron","Halduron Wolkenläufer","Kael'thas Sonnenwanderer","Rommath"], correct: "Lor'themar Theron" },
        { question: "Welcher Charakter war ein Schüler von Illidan und tauchte in der Festung der Stürme auf?", answers: ["Kael'thas Sonnenwanderer","Akama","Lady Vashj","Prinz Malchezaar"], correct: "Kael'thas Sonnenwanderer" },
        { question: "Wer ist der Anführer der Kirin Tor und der Stadt Dalaran?", answers: ["Archimonde","Vargoth","Kael'thas","Jaina Proudmoore"], correct: "Jaina Proudmoore" },
        { question: "Welche Fraktion in Wrath of the Lich King erlaubte den Spielern, sich in ein Nashorn zu verwandeln?", answers: ["Die Söhne Hodirs","Der Kalu'ak","Die Orakel","Die Argentum-Vorhut"], correct: "Die Orakel" },
        { question: "Welches der folgenden ist kein Pakt in Shadowlands?", answers: ["Die Goldene Lotus","Die Kyrianer","Die Nekrolords","Die Nachtfae"], correct: "Die Goldene Lotus" },
        { question: "Wie heißt der schwarze Drache, der als neuer Erdenwächter bestimmt wurde?", answers: ["Nozdormu","Alexstrasza","Sabellian","Ebyssian"], correct: "Ebyssian" },
        { question: "Welcher NPC in den Sümpfen des Elends ist eine Anspielung auf den Schauspieler Tom Cruise?", answers: ["Tom Cruisemissile","Ace Ventura","David Hasselhoff","Tom Twiddle"], correct: "Tom Cruisemissile" },
        { question: "Welche der vier Elementarlords ist die Herrin des Wassers?", answers: ["Ragnaros","Therazane","Al'Akir","Neptulon"], correct: "Neptulon" },
        { question: "Was ist der Name der Organisation, die sich dem Kampf gegen die Geißel verschrieben hat?", answers: ["Der Silberne Bund","Die Argentum-Dämmerung","Die Hand von Argus","Die Allianz"], correct: "Die Argentum-Dämmerung" },
        { question: "Wer ist der Bruder von Jaina Proudmoore?", answers: ["Daelin","Tandred","Arthas","Varian"], correct: "Tandred" },
        { question: "Welcher legendäre Anführer der Horde starb im Kampf gegen Garrosh Höllschrei?", answers: ["Vol'jin","Thrall","Cairne Bluthuf","Saurfang"], correct: "Cairne Bluthuf" },
        { question: "Welche Fraktion ist der Hauptgegner in Warlords of Draenor?", answers: ["Die Brennende Legion","Die Geißel","Die Eiserne Horde","Die Alte Götter"], correct: "Die Eiserne Horde" },
        { question: "Welcher Charakter ist der Erzfeind von Illidan Sturmgrimm?", answers: ["Malfurion Sturmgrimm","Kil'jaeden","Maiev Schattensang","Sargeras"], correct: "Kil'jaeden" },
        { question: "Wer sagte den berühmten Satz 'Die Zeit ist ein Fluss, und ich bin das Ufer'?", answers: ["Chromie","Nozdormu","Ysera","Alexstrasza"], correct: "Nozdormu" }
    ],
    "Items & Currencys": [
        { question: "Welches legendäre Item bekam man in Wrath of the Lich King?", answers: ["Donnerzorn","Schattengram","Atiesh","Sulfuras"], correct: "Schattengram" },
        { question: "Welche Waffe führte Illidan im Schwarzen Tempel?", answers: ["Schattengram","Aschenbringer","Kriegsgleven von Azzinoth","Frostgram"], correct: "Kriegsgleven von Azzinoth" },
        { question: "Welche Farbe hat das Transmogrifikations-Set vom Scharlachroten Kloster?", answers: ["Blau","Grün","Rot","Violett"], correct: "Rot" },
        { question: "Welche Währung wurde in Classic hauptsächlich für PvP-Belohnungen verwendet?", answers: ["Ehre","Marken","Tapferkeitspunkte","Abzeichen"], correct: "Ehre" },
        { question: "Wie hieß die Währung in Warlords of Draenor, die man für Garnisons-Upgrades brauchte?", answers: ["Tapferkeitspunkte","Erz","Gold","Garnisonsressourcen"], correct: "Garnisonsressourcen" },
        { question: "Welche Währung wurde in Burning Crusade zur Beschaffung von T4- und T5-Gegenständen verwendet?", answers: ["Abzeichen der Gerechtigkeit","Tapferkeitspunkte","Rufmarken","Heldentumspunkte"], correct: "Abzeichen der Gerechtigkeit" },
        { question: "Welche Ressource wurde in Legion für die Aufwertung der Artefaktwaffen verwendet?", answers: ["Artefaktmacht","Seelenmacht","Legendäre Scherben","Azerit"], correct: "Artefaktmacht" },
        { question: "Welche Ressource wurde in Battle for Azeroth zur Verbesserung der Halskette 'Herz von Azeroth' verwendet?", answers: ["Titanenresiduum","Artefaktmacht","Seelenmacht","Azerit"], correct: "Azerit" },
        { question: "Welcher legendäre Gegenstand war in Cataclysm die herstellbare Waffe für Schurken?", answers: ["Donnerzorn","Fänge des Vaters","Schattengram","Atiesh"], correct: "Fänge des Vaters" },
        { question: "Welches Material wurde in Classic für die Herstellung von epischen Gegenständen benötigt und war sehr selten?", answers: ["Arkanitbarren","Teufelsstoff","Echtsilberbarren","Elementarerde"], correct: "Arkanitbarren" },
        { question: "Welche legendäre Waffe konnten nur Jäger in Classic durch eine Questreihe erwerben?", answers: ["Atiesh","Thori'dal","Rhok'delar","Schattengram"], correct: "Rhok'delar" },
        { question: "Welches neue 'Tier' wurde in Cataclysm für Berufe eingeführt?", answers: ["Großmeister","Mystisch","Legendär","Erhaben"], correct: "Großmeister" },
        { question: "Welche Waffe ist die Artefaktwaffe des Schutz-Paladins?", answers: ["Die Aschenbringer","Verdammnishauer","Schicksalsklinge des Zorns","Schwert des Lichts"], correct: "Schicksalsklinge des Zorns" },
        { question: "Wie heißt die Währung, die man in Zereth Mortis für das Herstellen von Gegenständen sammelte?", answers: ["Seelenasche","Kosmische Energie","Katalysator-Energie","Trost der Ersten"], correct: "Trost der Ersten" },
        { question: "Wie heißt das System, dass die Spieler zum Rennen mit ihren Drachen über die Dracheninseln nutzt?", answers: ["Drachenreiten","Flugbeherrschung","Drachenflug","Himmelsritt"], correct: "Drachenreiten" },
        { question: "Welches Item aus Classic war eine Anspielung auf die TV-Serie 'A-Team'?", answers: ["Die Verdammnisklinge","Mr. T's Fäuste","Colonel Kurzen's Klinge","Das B.A.R. Tool"], correct: "Mr. T's Fäuste" },
        { question: "Welche legendäre Waffe führte Tirion Fordring?", answers: ["Frostgram","Aschenbringer","Donnerzorn","Verdammnishammer"], correct: "Aschenbringer" },
        { question: "Was ist die Währung, die man für das Töten von Gegner im PvP erhält?", answers: ["Tapferkeitspunkte","Eroberungspunkte","Ehre","Abzeichen"], correct: "Ehre" },
        { question: "Welches Addon führte das System des 'Kriegsgeschmiedet' ein?", answers: ["Mists of Pandaria","Warlords of Draenor","Legion","Shadowlands"], correct: "Warlords of Draenor" },
        { question: "Welche Währung ersetzte die Abzeichen der Gerechtigkeit in Wrath of the Lich King?", answers: ["Ehre","Tapferkeitspunkte","Embleme","Eroberungspunkte"], correct: "Embleme" },
        { question: "Welche Währung wurde in Cataclysm zur Beschaffung von PvP-Ausrüstung verwendet?", answers: ["Ehre","Tapferkeitspunkte","Eroberungspunkte","Gerechtigkeitspunkte"], correct: "Eroberungspunkte" },
        { question: "Welche Ressource wurde in Shadowlands zur Aufwertung von Legendären Gegenständen verwendet?", answers: ["Kosmische Energie","Seelenasche","Trost der Ersten","Flugsteine"], correct: "Seelenasche" },
        { question: "Welche Währung wurde in Dragonflight für das Aufwerten von Rüstung verwendet?", answers: ["Trost der Ersten","Flugsteine","Tapferkeitspunkte","Garnisonsressourcen"], correct: "Flugsteine" },
        { question: "Welche Währung wurde in Battle for Azeroth zur Verbesserung von Rüstungsteilen verwendet?", answers: ["Seelenasche","Azerit","Titanenresiduum","Eroberungspunkte"], correct: "Titanenresiduum" },
        { question: "Welches neue Material wurde in Mists of Pandaria für die Herstellung von Waffen und Rüstungen eingeführt?", answers: ["Geist der Harmonie","Titanenstaub","Elementium","Trillium"], correct: "Geist der Harmonie" },
        { question: "Welche Währung wurde in Classic für den Kauf von T0.5 Set-Teilen verwendet?", answers: ["Ehre","Gold und Materialen","Abzeichen der Gerechtigkeit","Dungeon-Marken"], correct: "Gold und Materialen" },
        { question: "Welche Währung wurde in Warlords of Draenor für den Kauf von Berufs-Rezepten verwendet?", answers: ["Garnisonsressourcen","Geheimnisse von Draenor","Erz","Wildes Blut"], correct: "Geheimnisse von Draenor" },
        { question: "Welches legendäre Item konnte man in Battle for Azeroth erhalten?", answers: ["Herz von Azeroth","Legendärer Umhang","Die Halskette der Titanen","Der legendäre Ring"], correct: "Herz von Azeroth" },
        { question: "Welche Währung wurde in Warlords of Draenor für den Kauf von PvP-Ausrüstung verwendet?", answers: ["Garnisonsressourcen","Eroberungspunkte","Ehre","Tapferkeitspunkte"], correct: "Eroberungspunkte" },
        { question: "Welche Währung wurde in The Burning Crusade für das Kaufen von Flugreittieren verwendet?", answers: ["Abzeichen der Gerechtigkeit","Gold","Tapferkeitspunkte","Eroberungspunkte"], correct: "Gold" },
    ],
};

// Zur Abwärtskompatibilität für das "Hauptquiz" (alle Fragen)
window.allQuestions = [].concat(
    window.quizCategories["Allgemein"],
    window.quizCategories["AddOns"],
    window.quizCategories["Pets and Mounts"],
    window.quizCategories["Achievements"],
    window.quizCategories["Races and Classes"],
    window.quizCategories["Dungeons and Raids"],
    window.quizCategories["Quests and Regions"],
    window.quizCategories["NPCs"],
    window.quizCategories["Items & Currencys"]
);